interface=wlan0
country_code=us
ieee80211n=1
ieee80211ac=1
hw_mode=a
channel=36
driver=nl80211
####ht_capab=[HT40+][SHORT-GI-40][DSSS_CCK-40]
####vht_capab=[SHORT-GI-80][RX-STBC-2BY1]
####vht_oper_chwidth=1
####vht_oper_centr_freq_seg0_idx=42
#require_ht=1
#require_vht=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ssid=StellaVita_A59046
